### ISSUE TITLE
密码错误

### ISSUE THREAD

**Issue by hezhicai1** [OrionAAAA/cpdaily_auto_signin#1]
这个是学校通用吗 ，密码没错啊

**Comment by A0CBEB339CB02898** [comment]
这个脚本适用于广东海洋大学的，其他学校的话可能要改成对应的域名才可以。如果是本校的话确认一次所说的账号密码对应的是https://authserver.gdou.edu.cn/authserver/login 这个页面的账号密码。

**Comment by hezhicai1** [comment]
嗯嗯

**Comment by hezhicai1** [comment]
在哪里修改域名

**Comment by OrionAAAA** [comment]
在login.py的login_url和captcha_url。还有其他问题你加我qq769908669吧
